groups:
- name: basic
  rules:
  - alert: PrometheusTargetDown
    expr: up == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Target down: {{ $labels.instance }}"
      description: "Job {{ $labels.job }} target {{ $labels.instance }} has been down for 2m."
