apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    istio-injection: enabled  # This namespace WILL get sidecars
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: test-app
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - name: http
    port: 8000
    targetPort: 80
  - name: http-monitoring
    port: 15090
    targetPort: 15090