apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-injection-sa
  namespace: vaultinaction
  labels:
    app.kubernetes.io/name: vault-secret-injection
    app.kubernetes.io/part-of: vault-in-action
