apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  # Argo CD manages Argo CD via Helm, using values from this repo
  sources:
    # 1) Helm chart source
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.3.6
      helm:
        valueFiles:
          - $values/istio/infrastructure/argocd/argo-value/argocd-values.yaml
    # 2) Git repo source providing the values file (referenced above via $values/...)
    - repoURL: https://github.com/visheshofficial/observability
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
