apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-injection-sa
  namespace: vaultinaction
  labels:
    app.kubernetes.io/name: vault-secret-injection
    app.kubernetes.io/part-of: vault-in-action
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret-injection
  namespace: vaultinaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-secret-injection
  template:
    metadata:
      labels:
        app: vault-secret-injection
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-secret-injection-role"
        # vault.hashicorp.com/address: "http://vault.vault.svc:8200"
        # Map logical file name -> secret path (KV v2 needs /data/)
        vault.hashicorp.com/agent-inject-secret-app-creds-username: "secret/data/vault-secret-injection/app-creds"
        # Render template (KV v2 uses .Data.data)
        vault.hashicorp.com/agent-inject-template-app-creds-username: |
          {{- with secret "secret/data/vault-secret-injection/app-creds" -}}
          {{ .Data.data.Username }}
          {{- end }}
    spec:
      serviceAccountName: vault-secret-injection-sa
      containers:
        - name: vault-secret-injection
          image: busybox:1.36
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Waiting for /vault/secrets/app-creds-username ...";
              while [ ! -f /vault/secrets/app-creds-username ]; do sleep 1; done;
              echo "==== Rendered secret ====";
              ls /vault/secrets/app-creds-username;
              cat /vault/secrets/app-creds-username;
              echo "=========================";
              echo "Sleeping...";
              sleep 3600
