# Values for Istio Egress Gateway
name: istio-egressgateway
labels:
  istio: egressgateway
service:
  type: ClusterIP
  ports:
    - name: tls
      port: 15443
      targetPort: 15443
    - name: status-port
      port: 15021
      targetPort: 15021
