apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: demo
  labels:
    app: demo
data:
  message: "Hello from ArgoCD demo!"
