apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: istioinaction-ch01
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: curlimages/curl:8.8.0
          command: ["sh", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
